"""
    CODE_TO_LANG::Dict{String,String}

    A constant dictionary maps 51 language codes to their names
"""
const CODE_TO_LANG =
Dict{String,String}(
    "sk" => "Slovak",
    "id" => "Indonesian",
    "lv" => "Latvian",
    "ca" => "Catalan",
    "sl" => "Slovenian",
    "hi" => "Hindi",
    "sa" => "Sanskrit",
    "el" => "Greek",
    "nl" => "Dutch",
    "hr" => "Croatian",
    "ug" => "Uyghur",
    "gl" => "Galician",
    "ru" => "Russian",
    "ur" => "Urdu",
    "en" => "English",
    "bxr" => "Buryat",
    "pl" => "Polish",
    "cop" => "Coptic",
    "grc" => "Ancient_Greek",
    "ta" => "Tamil",
    "eu" => "Basque",
    "fa" => "Persian",
    "da" => "Danish",
    "tr" => "Turkish",
    "it" => "Italian",
    "got" => "Gothic",
    "ko" => "Korean",
    "fi" => "Finnish",
    "fo" => "Faroese",
    "zh" => "Chinese",
    "pt" => "Portuguese",
    "ro" => "Romanian",
    "ar" => "Arabic",
    "de" => "German",
    "bg" => "Bulgarian",
    "la" => "Latin",
    "uk" => "Ukrainian",
    "et" => "Estonian",
    "cs" => "Czech",
    "ja" => "Japanese",
    "sv" => "Swedish",
    "no" => "Norwegian",
    "fr" => "French",
    "ga" => "Irish",
    "es" => "Spanish",
    "vi" => "Vietnamese",
    "he" => "Hebrew",
    "hu" => "Hungarian",
    "kk" => "Kazakh",
    "am" => "Amharic",
    "cu" => "Old_Church_Slavonic"
);
